spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${FLYWAY_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
logging:
  pattern:
    console: "[%level][%thread][%logger{0}:%line] - %msg%n"
secret:
  kakao-client-id: ${KAKAO_CLIENT_ID}
  kakao-redirect-url: ${KAKAO_REDIRECT_URL}
  apple-key-id: ${APPLE_KEY_ID}
  apple-keyfile-value: ${APPLE_KEYFILE_value}
  apple-team-id: ${APPLE_TEAM_ID}
  apple-client-id: ${APPLE_CLIENT_ID}
  apple-native-client-id: ${APPLE_NATIVE_CLIENT_ID}
  google-firebase-secret-value: ${GOOGLE_FIREBASE_SECRET_VALUE}
server:
  servlet:
    context-path: '/api'
  port: ${SERVER_PORT}
token:
  secret: ${AUTH_SECRET}
  expiration:
    access: 86400
    refresh: 384000
